name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"  # every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Update datas and deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate Snake GIF / SVG
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@master
        with:
          github_user_name: zhiminnnnn
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages (output branch)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
